In [ ]:
## Numpy : match calculations 

In [1]:
!pip install numpy

In [8]:
import numpy as np

In [9]:
len(dir(np))

608

In [10]:
type([1,2,3,4,5])

list

In [12]:
# Numpy array from list 

arr = np.array([1,2,3,4,5])
print(arr)
type(arr)

[1 2 3 4 5]


numpy.ndarray

In [14]:
# Numpy array from tuple

arr = np.array((1,2,3,4,5))
print(arr)
type(arr)

[1 2 3 4 5]


numpy.ndarray

In [15]:
# Numpy array from set

arr = np.array({1,2,3,4,5,5,5,3,3,31})
print(arr)
type(arr)

{1, 2, 3, 4, 5, 31}


numpy.ndarray

In [25]:
# Numpy array : attributes 

arr = np.array([1,2,3,4,5.1])

print(arr)
print(arr.ndim) # dimension of the array
print(arr.shape) # Number of rows & columns 
print(arr.size) # total number of elements
print(arr.dtype) # the data type of contents of the array
print(arr.itemsize) # number of bytes used to store the array elements

[1.  2.  3.  4.  5.1]
1
(5,)
5
float64
8


In [26]:
# Numpy array : attributes 

arr = np.array([[1,2,3,4,5],[10,20,30,40,50],[100,200,300,400,500]])

print(arr)
print(arr.ndim) # dimension of the array
print(arr.shape) # Number of rows & columns 
print(arr.size) # total number of elements
print(arr.dtype) # the data type of contents of the array
print(arr.itemsize) # number of bytes used to store the array elements

[[  1   2   3   4   5]
 [ 10  20  30  40  50]
 [100 200 300 400 500]]
2
(3, 5)
15
int32
4


In [27]:
## ones() and zeros()

arr = np.ones((5,5))
print(arr)

arr = np.zeros((5,5))
print(arr)


[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [32]:
## copy 

import numpy as np 
a = np.array([1,2,3])
print(id(a))

b = a
print(id(b))

c = a.copy()
print(id(c))

a[0]= 858585

print(a)
print(b)
print(c)


2055766391280
2055766391280
2055774891824
[858585      2      3]
[858585      2      3]
[1 2 3]


In [35]:
# arange 

import numpy as np 
arr = np.arange(0,20)
print(arr)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


In [37]:
# arange 

import numpy as np 
arr = np.arange(0,21,2)
print(arr)

[ 0  2  4  6  8 10 12 14 16 18 20]


In [54]:
# linspace 

import numpy as np 
arr = np.linspace(0,100,5)
print(arr)

[  0.  25.  50.  75. 100.]


In [42]:
## Arithmetic operators 

a = np.array([1,2,3,4,5])
b = np.array([10,20,30,40,50])

print(a+b)
print(a-b)
print(a*b)
print(a/b)

[11 22 33 44 55]
[ -9 -18 -27 -36 -45]
[ 10  40  90 160 250]
[0.1 0.1 0.1 0.1 0.1]


In [57]:
## Matrix product 

import numpy as np 
a = np.arange(0,9).reshape(3,3)
b = np.ones((3,3))

print(a)
print(b)

print(np.dot(a,b))

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[[ 3.  3.  3.]
 [12. 12. 12.]
 [21. 21. 21.]]


In [61]:
np.arange(0,9).reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [65]:
## Universal functions 

import numpy as np 

arr = np.array([4,9,16,25])

print(arr)
print(np.sqrt(arr))
print(np.log(arr))
print(np.sqrt(arr))

[ 4  9 16 25]
[2. 3. 4. 5.]
[1.38629436 2.19722458 2.77258872 3.21887582]
[2. 3. 4. 5.]


In [66]:
## Aggregate functions 

print(arr.sum())
print(arr.min())
print(arr.max())
print(arr.mean())
print(arr.std())

54
4
25
13.5
7.88986691902975


In [77]:
## Logical functions

arr = np.array([[True,False],[True,True]])
print(arr)

# Overall 
print(np.all([arr]))

print(np.all([arr], axis = 1))

[[ True False]
 [ True  True]]
False
[[ True False]]


In [78]:
## Logical functions

arr = np.array([[True,False],[True,True]])
print(arr)

# Overall 
print(np.any([arr]))

print(np.any([arr], axis = 1))

[[ True False]
 [ True  True]]
True
[[ True  True]]
