In [ ]:
# Pandas 

In [1]:
# Series 

data = [10,20,30,40,50] # it can be a list, tuple, dictionary, set, numpy array

import pandas as pd 

sr = pd.Series(data, index = [100,200,300,400,500])

In [2]:
sr

100    10
200    20
300    30
400    40
500    50
dtype: int64

In [3]:
# Data Frame
import numpy as np
data = np.array([[1,2,3,4,5],[10,20,30,40,50]])

print(data)
print(data.ndim)

[[ 1  2  3  4  5]
 [10 20 30 40 50]]
2


In [4]:
df = pd.DataFrame(data)
df

0   1   2   3   4
0   1   2   3   4   5
1  10  20  30  40  50

In [5]:
df = pd.DataFrame(data, index=['row1','row2'])
df

0   1   2   3   4
row1   1   2   3   4   5
row2  10  20  30  40  50

In [6]:
df = pd.DataFrame(data, index=['row1','row2'], columns = ['col1','col2','col3','col4','col5'])
df

col1  col2  col3  col4  col5
row1     1     2     3     4     5
row2    10    20    30    40    50

In [7]:
## Read CSV files 

df = pd.read_csv("C:/Users/AdmiN/Desktop/EK/B1_15May/mtcars.csv")
df

Unnamed: 0   mpg  cyl   disp   hp  drat     wt   qsec  vs  am  \
0             Mazda RX4  21.0    6  160.0  110  3.90  2.620  16.46   0   1   
1         Mazda RX4 Wag  21.0    6  160.0  110  3.90  2.875  17.02   0   1   
2            Datsun 710  22.8    4  108.0   93  3.85  2.320  18.61   1   1   
3        Hornet 4 Drive  21.4    6  258.0  110  3.08  3.215  19.44   1   0   
4     Hornet Sportabout  18.7    8  360.0  175  3.15  3.440  17.02   0   0   
5               Valiant  18.1    6  225.0  105  2.76  3.460  20.22   1   0   
6            Duster 360  14.3    8  360.0  245  3.21  3.570  15.84   0   0   
7             Merc 240D  24.4    4  146.7   62  3.69  3.190  20.00   1   0   
8              Merc 230  22.8    4  140.8   95  3.92  3.150  22.90   1   0   
9              Merc 280  19.2    6  167.6  123  3.92  3.440  18.30   1   0   
10            Merc 280C  17.8    6  167.6  123  3.92  3.440  18.90   1   0   
11           Merc 450SE  16.4    8  275.8  180  3.07  4.070  17.40   0   0   
12           Merc 450SL  17.3    8  275.8  180  3.07  3.730  17.60   0   0   
13          Merc 450SLC  15.2    8  275.8  180  3.07  3.780  18.00   0   0   
14   Cadillac Fleetwood  10.4    8  472.0  205  2.93  5.250  17.98   0   0   
15  Lincoln Continental  10.4    8  460.0  215  3.00  5.424  17.82   0   0   
16    Chrysler Imperial  14.7    8  440.0  230  3.23  5.345  17.42   0   0   
17             Fiat 128  32.4    4   78.7   66  4.08  2.200  19.47   1   1   
18          Honda Civic  30.4    4   75.7   52  4.93  1.615  18.52   1   1   
19       Toyota Corolla  33.9    4   71.1   65  4.22  1.835  19.90   1   1   
20        Toyota Corona  21.5    4  120.1   97  3.70  2.465  20.01   1   0   
21     Dodge Challenger  15.5    8  318.0  150  2.76  3.520  16.87   0   0   
22          AMC Javelin  15.2    8  304.0  150  3.15  3.435  17.30   0   0   
23           Camaro Z28  13.3    8  350.0  245  3.73  3.840  15.41   0   0   
24     Pontiac Firebird  19.2    8  400.0  175  3.08  3.845  17.05   0   0   
25            Fiat X1-9  27.3    4   79.0   66  4.08  1.935  18.90   1   1   
26        Porsche 914-2  26.0    4  120.3   91  4.43  2.140  16.70   0   1   
27         Lotus Europa  30.4    4   95.1  113  3.77  1.513  16.90   1   1   
28       Ford Pantera L  15.8    8  351.0  264  4.22  3.170  14.50   0   1   
29         Ferrari Dino  19.7    6  145.0  175  3.62  2.770  15.50   0   1   
30        Maserati Bora  15.0    8  301.0  335  3.54  3.570  14.60   0   1   
31           Volvo 142E  21.4    4  121.0  109  4.11  2.780  18.60   1   1   

    gear  carb  
0      4     4  
1      4     4  
2      4     1  
3      3     1  
4      3     2  
5      3     1  
6      3     4  
7      4     2  
8      4     2  
9      4     4  
10     4     4  
11     3     3  
12     3     3  
13     3     3  
14     3     4  
15     3     4  
16     3     4  
17     4     1  
18     4     2  
19     4     1  
20     3     1  
21     3     2  
22     3     2  
23     3     4  
24     3     2  
25     4     1  
26     5     2  
27     5     2  
28     5     4  
29     5     6  
30     5     8  
31     4     2

In [8]:
## Read Excel files 

df = pd.read_excel("C:/Users/AdmiN/Desktop/EK/B1_15May/mtcars.xlsx")
df

#pd.read_csv("C:/Users/AdmiN/Desktop/EK/B1_15May/mtcars.csv")

FileNotFoundError: [Errno 2] No such file or directory: 'C:/Users/AdmiN/Desktop/EK/B1_15May/mtcars.xlsx'

In [9]:
df.head()

Unnamed: 0   mpg  cyl   disp   hp  drat     wt   qsec  vs  am  gear  \
0          Mazda RX4  21.0    6  160.0  110  3.90  2.620  16.46   0   1     4   
1      Mazda RX4 Wag  21.0    6  160.0  110  3.90  2.875  17.02   0   1     4   
2         Datsun 710  22.8    4  108.0   93  3.85  2.320  18.61   1   1     4   
3     Hornet 4 Drive  21.4    6  258.0  110  3.08  3.215  19.44   1   0     3   
4  Hornet Sportabout  18.7    8  360.0  175  3.15  3.440  17.02   0   0     3   

   carb  
0     4  
1     4  
2     1  
3     1  
4     2

In [10]:
df.tail()

Unnamed: 0   mpg  cyl   disp   hp  drat     wt  qsec  vs  am  gear  \
27    Lotus Europa  30.4    4   95.1  113  3.77  1.513  16.9   1   1     5   
28  Ford Pantera L  15.8    8  351.0  264  4.22  3.170  14.5   0   1     5   
29    Ferrari Dino  19.7    6  145.0  175  3.62  2.770  15.5   0   1     5   
30   Maserati Bora  15.0    8  301.0  335  3.54  3.570  14.6   0   1     5   
31      Volvo 142E  21.4    4  121.0  109  4.11  2.780  18.6   1   1     4   

    carb  
27     2  
28     4  
29     6  
30     8  
31     2

In [11]:
df[["mpg","disp"]]

mpg   disp
0   21.0  160.0
1   21.0  160.0
2   22.8  108.0
3   21.4  258.0
4   18.7  360.0
5   18.1  225.0
6   14.3  360.0
7   24.4  146.7
8   22.8  140.8
9   19.2  167.6
10  17.8  167.6
11  16.4  275.8
12  17.3  275.8
13  15.2  275.8
14  10.4  472.0
15  10.4  460.0
16  14.7  440.0
17  32.4   78.7
18  30.4   75.7
19  33.9   71.1
20  21.5  120.1
21  15.5  318.0
22  15.2  304.0
23  13.3  350.0
24  19.2  400.0
25  27.3   79.0
26  26.0  120.3
27  30.4   95.1
28  15.8  351.0
29  19.7  145.0
30  15.0  301.0
31  21.4  121.0

In [12]:
df.drop('wt', axis = 'columns').head()

Unnamed: 0   mpg  cyl   disp   hp  drat   qsec  vs  am  gear  carb
0          Mazda RX4  21.0    6  160.0  110  3.90  16.46   0   1     4     4
1      Mazda RX4 Wag  21.0    6  160.0  110  3.90  17.02   0   1     4     4
2         Datsun 710  22.8    4  108.0   93  3.85  18.61   1   1     4     1
3     Hornet 4 Drive  21.4    6  258.0  110  3.08  19.44   1   0     3     1
4  Hornet Sportabout  18.7    8  360.0  175  3.15  17.02   0   0     3     2

In [18]:
# Slice 
df["Unnamed: 0"].head()

0            Mazda RX4
1        Mazda RX4 Wag
2           Datsun 710
3       Hornet 4 Drive
4    Hornet Sportabout
Name: Unnamed: 0, dtype: object

In [19]:
# Mazda RX4 -- replace 

df["Unnamed: 0"][0] = 'New_Car'
df.head()

C:\Users\AdmiN\AppData\Local\Temp\ipykernel_9068\313457594.py:3: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["Unnamed: 0"][0] = 'New_Car'


Unnamed: 0   mpg  cyl   disp   hp  drat     wt   qsec  vs  am  gear  \
0            New_Car  21.0    6  160.0  110  3.90  2.620  16.46   0   1     4   
1      Mazda RX4 Wag  21.0    6  160.0  110  3.90  2.875  17.02   0   1     4   
2         Datsun 710  22.8    4  108.0   93  3.85  2.320  18.61   1   1     4   
3     Hornet 4 Drive  21.4    6  258.0  110  3.08  3.215  19.44   1   0     3   
4  Hornet Sportabout  18.7    8  360.0  175  3.15  3.440  17.02   0   0     3   

   carb  
0     4  
1     4  
2     1  
3     1  
4     2

In [22]:
df[df["cyl"] > 6]

Unnamed: 0   mpg  cyl   disp   hp  drat     wt   qsec  vs  am  \
4     Hornet Sportabout  18.7    8  360.0  175  3.15  3.440  17.02   0   0   
6            Duster 360  14.3    8  360.0  245  3.21  3.570  15.84   0   0   
11           Merc 450SE  16.4    8  275.8  180  3.07  4.070  17.40   0   0   
12           Merc 450SL  17.3    8  275.8  180  3.07  3.730  17.60   0   0   
13          Merc 450SLC  15.2    8  275.8  180  3.07  3.780  18.00   0   0   
14   Cadillac Fleetwood  10.4    8  472.0  205  2.93  5.250  17.98   0   0   
15  Lincoln Continental  10.4    8  460.0  215  3.00  5.424  17.82   0   0   
16    Chrysler Imperial  14.7    8  440.0  230  3.23  5.345  17.42   0   0   
21     Dodge Challenger  15.5    8  318.0  150  2.76  3.520  16.87   0   0   
22          AMC Javelin  15.2    8  304.0  150  3.15  3.435  17.30   0   0   
23           Camaro Z28  13.3    8  350.0  245  3.73  3.840  15.41   0   0   
24     Pontiac Firebird  19.2    8  400.0  175  3.08  3.845  17.05   0   0   
28       Ford Pantera L  15.8    8  351.0  264  4.22  3.170  14.50   0   1   
30        Maserati Bora  15.0    8  301.0  335  3.54  3.570  14.60   0   1   

    gear  carb  
4      3     2  
6      3     4  
11     3     3  
12     3     3  
13     3     3  
14     3     4  
15     3     4  
16     3     4  
21     3     2  
22     3     2  
23     3     4  
24     3     2  
28     5     4  
30     5     8

In [ ]:
## iloc & loc

In [2]:
# Data Frame
import pandas as pd
import numpy as np
data = np.array([[1,2,3,4,5],[10,20,30,40,50]])

print(data)
print(data.ndim)

df = pd.DataFrame(data, index=['row1','row2'], columns = ['col1','col2','col3','col4','col5'])
df

[[ 1  2  3  4  5]
 [10 20 30 40 50]]
2


col1  col2  col3  col4  col5
row1     1     2     3     4     5
row2    10    20    30    40    50

In [3]:
df.to_csv("New_file.csv")

In [ ]:
df.iloc[ : , : ]

In [34]:
# Access using index location 

df.iloc[ 0 : 1 , 2 :  ]

col3  col4  col5
row1     3     4     5

In [35]:
## Access using name location

df.loc['row1':,'col2': ]

col2  col3  col4  col5
row1     2     3     4     5
row2    20    30    40    50

In [36]:
## Read CSV files 

df = pd.read_csv("C:/Users/AdmiN/Desktop/EK/B1_15May/mtcars.csv")
df

Unnamed: 0   mpg  cyl   disp   hp  drat     wt   qsec  vs  am  \
0             Mazda RX4  21.0    6  160.0  110  3.90  2.620  16.46   0   1   
1         Mazda RX4 Wag  21.0    6  160.0  110  3.90  2.875  17.02   0   1   
2            Datsun 710  22.8    4  108.0   93  3.85  2.320  18.61   1   1   
3        Hornet 4 Drive  21.4    6  258.0  110  3.08  3.215  19.44   1   0   
4     Hornet Sportabout  18.7    8  360.0  175  3.15  3.440  17.02   0   0   
5               Valiant  18.1    6  225.0  105  2.76  3.460  20.22   1   0   
6            Duster 360  14.3    8  360.0  245  3.21  3.570  15.84   0   0   
7             Merc 240D  24.4    4  146.7   62  3.69  3.190  20.00   1   0   
8              Merc 230  22.8    4  140.8   95  3.92  3.150  22.90   1   0   
9              Merc 280  19.2    6  167.6  123  3.92  3.440  18.30   1   0   
10            Merc 280C  17.8    6  167.6  123  3.92  3.440  18.90   1   0   
11           Merc 450SE  16.4    8  275.8  180  3.07  4.070  17.40   0   0   
12           Merc 450SL  17.3    8  275.8  180  3.07  3.730  17.60   0   0   
13          Merc 450SLC  15.2    8  275.8  180  3.07  3.780  18.00   0   0   
14   Cadillac Fleetwood  10.4    8  472.0  205  2.93  5.250  17.98   0   0   
15  Lincoln Continental  10.4    8  460.0  215  3.00  5.424  17.82   0   0   
16    Chrysler Imperial  14.7    8  440.0  230  3.23  5.345  17.42   0   0   
17             Fiat 128  32.4    4   78.7   66  4.08  2.200  19.47   1   1   
18          Honda Civic  30.4    4   75.7   52  4.93  1.615  18.52   1   1   
19       Toyota Corolla  33.9    4   71.1   65  4.22  1.835  19.90   1   1   
20        Toyota Corona  21.5    4  120.1   97  3.70  2.465  20.01   1   0   
21     Dodge Challenger  15.5    8  318.0  150  2.76  3.520  16.87   0   0   
22          AMC Javelin  15.2    8  304.0  150  3.15  3.435  17.30   0   0   
23           Camaro Z28  13.3    8  350.0  245  3.73  3.840  15.41   0   0   
24     Pontiac Firebird  19.2    8  400.0  175  3.08  3.845  17.05   0   0   
25            Fiat X1-9  27.3    4   79.0   66  4.08  1.935  18.90   1   1   
26        Porsche 914-2  26.0    4  120.3   91  4.43  2.140  16.70   0   1   
27         Lotus Europa  30.4    4   95.1  113  3.77  1.513  16.90   1   1   
28       Ford Pantera L  15.8    8  351.0  264  4.22  3.170  14.50   0   1   
29         Ferrari Dino  19.7    6  145.0  175  3.62  2.770  15.50   0   1   
30        Maserati Bora  15.0    8  301.0  335  3.54  3.570  14.60   0   1   
31           Volvo 142E  21.4    4  121.0  109  4.11  2.780  18.60   1   1   

    gear  carb  
0      4     4  
1      4     4  
2      4     1  
3      3     1  
4      3     2  
5      3     1  
6      3     4  
7      4     2  
8      4     2  
9      4     4  
10     4     4  
11     3     3  
12     3     3  
13     3     3  
14     3     4  
15     3     4  
16     3     4  
17     4     1  
18     4     2  
19     4     1  
20     3     1  
21     3     2  
22     3     2  
23     3     4  
24     3     2  
25     4     1  
26     5     2  
27     5     2  
28     5     4  
29     5     6  
30     5     8  
31     4     2