In [ ]:
## Indexing in numpy array 

In [1]:
import numpy as np
arr = np.arange(21,26)

arr

array([21, 22, 23, 24, 25])

In [5]:
## Get 22
print(arr[1])
print(arr[2])
print(arr[3])

22
23
24


In [7]:
print(arr[1:4])
print(arr[-4:-1])

[22 23 24]
[22 23 24]


In [8]:
## Indexing 2D 

a = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(a)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [9]:
a[0:2,0:2]

array([[1, 2],
       [4, 5]])

In [11]:
a[1:3,1:3]

array([[5, 6],
       [8, 9]])

In [13]:
a[1:2,1:2]

array([[5]])

In [15]:
a[-2:-1,-2:-1]

array([[5]])

In [17]:
## Changing the shape of the array 

a = np.array([1,2,3,4,5,6,7,8,9])
a

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [26]:
print(a.reshape(3,3))
print(a)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[1 2 3 4 5 6 7 8 9]


In [27]:
print(a.resize(3,3))
print(a)

None
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [28]:
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [37]:
## ravel 

a = np.array([1,2,3,4,5,6,7,8,9]).reshape(3,3)
print(a)
print(a.ndim)
print(a.ravel())
print(a)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
2
[1 2 3 4 5 6 7 8 9]
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [34]:
## Transpose 
a = np.arange(12).reshape(3,4)
print(a)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [36]:
np.transpose(a)

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [38]:
## Joining the arrays 

a = np.array([[1,2],[3,4]])
b = np.array([[5,6]])

print(a)
print(b)

[[1 2]
 [3 4]]
[[5 6]]


In [41]:
## Axis = None 
np.concatenate((a,b), axis = None)

array([1, 2, 3, 4, 5, 6])

In [43]:
## Axis = 1
np.concatenate((a,b.T), axis = 1)

array([[1, 2, 5],
       [3, 4, 6]])

In [45]:
## Axis = 0
np.concatenate((a,b), axis = 0)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [49]:
### Stacking 
import numpy as np 
a = np.array([1,2,3])
b = np.array([10,20,30])

np.stack((a,b))

array([[ 1,  2,  3],
       [10, 20, 30]])

In [51]:
###  Column Stacking 
import numpy as np 
a = np.array([1,2,3])
b = np.array([10,20,30])
c = np.array([100,200,300])

np.column_stack((a,b,c))

array([[  1,  10, 100],
       [  2,  20, 200],
       [  3,  30, 300]])

In [ ]:
## Split arrays : split(), hsplit(), vsplit()

In [54]:
x = np.arange(9)
print(x)
np.split(x,3)

[0 1 2 3 4 5 6 7 8]


[array([0, 1, 2]), array([3, 4, 5]), array([6, 7, 8])]

In [55]:
a = np.arange(16).reshape((4,4))
print(a)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


In [58]:
np.hsplit(a,2)

[array([[ 0,  1],
        [ 4,  5],
        [ 8,  9],
        [12, 13]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11],
        [14, 15]])]

In [59]:
np.vsplit(a,2)

[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11],
        [12, 13, 14, 15]])]